name: Ruby CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev

      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          sudo ./ruby-build/install.sh

      - name: Install Ruby 3.1.4 manually
        run: |
          sudo mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Run your tests or script
        run: |
          bundle install
          bundle exec rake test # or your custom command
